WELCOME_MESSAGE = "Welcome to the Expense Tracking API."
NAMES_CONTAINS_ONLY_LETTERS = "Names must contain only letters."
USER_PASSWORD_MUST_BE_STRONG = "Password must be at least 8 characters long and include at least one letter, one number, and one special character."
USER_EMAIL_ALREADY_REGISTERED = "This email address is already registered."
USER_INVALID_ROLE_ID = "The provided role ID is invalid."
USER_CREATED_SUCCESSFULLY = "User has been created successfully."
USER_CREATION_FAILED = "An error occurred during user creation."

VALIDATION_ERROR = "There was a validation error."
INVALID_CREDENTIALS = "The provided credentials are invalid."
LOGIN_SUCCESSFUL = "Login was successful."
INTERNAL_SERVER_ERROR = "An internal server error occurred. Please try again later."
