WELCOME_MESSAGE = "Welcome to the Expense Tracking API."
NAMES_CONTAINS_ONLY_LETTERS = "Names must consist of letters only."
USER_PASSWORD_MUST_BE_STRONG = "Password must be at least 8 characters long and include at least one letter, one number, and one special character."
USER_EMAIL_ALREADY_REGISTERED = "This email address is already registered."
USER_INVALID_ROLE_ID = "The provided role ID is not valid."
USER_CREATED_SUCCESSFULLY = "User has been created successfully."
USER_CREATION_FAILED = "An error occurred during the creation of the user."

VALIDATION_ERROR = "A validation error occurred."
INVALID_CREDENTIALS = "The credentials provided are invalid."
LOGIN_SUCCESSFUL = "Login successful."
INTERNAL_SERVER_ERROR = "An internal server error occurred. Please try again later."
INVALID_SORT_FIELD = "The specified sort field is invalid."
INVALID_SORT_ORDER = "The specified sort order is invalid."
USERS_RETRIEVED_SUCCESSFULLY = "Users retrieved successfully."

MISSING_AUTHORIZATION_TOKEN = "Authorization token is missing or invalid."
INVALID_AUTHORIZATION_TOKEN = "The authorization token provided is invalid."
EXPIRED_AUTHORIZATION_TOKEN = "The authorization token has expired."
ACCESS_FORBIDDEN = "Access denied: You do not have the necessary permissions."

USER_NOT_EXIST = "User does not exist."
USER_DATA_FOUND = "User details found."
USER_UPDATED_SUCCESSFULLY = "User has been updated successfully."

PASSWORD_INCORRECT = "The provided password is incorrect."
PASSWORD_UPDATED_SUCCESSFULLY = "Password has been updated successfully."

USER_DELETED_SUCCESSFULLY = "User has been deleted successfully."

USER_ROLE_NAME_ALREADY_TAKEN = "The specified user role name already exists."
USER_ROLE_CREATED_SUCCESSFULLY = "User role has been created successfully."
USER_ROLES_LIST_GET_SUCCESSFULLY = "User roles list retrieved successfully."
USER_ROLE_NOT_EXIST = "The specified user role does not exist."
USER_ROLE_FOUND_SUCCESSFULL = "User role has been located successfully."
USER_ROLE_UPDATE_SUCCESSFULLY = "User role has been updated successfully."
USER_ROLE_IS_CONNECTED_WITH_USER_TABLE = "This user role is associated with existing users."
USER_ROLE_DELETE_SUCCESSFULLY = "User role has been deleted successfully."

CATEGORY_ALREADY_CREATED = "This category has already been created."
CATEGORY_CREATED_SUCCESSFULY = "Category created successfully."
CATEGORIES_LIST_GET_SUCCESSFULLY = "Category list retrieved successfully."
CATEGORIES_NOT_EXIST = "Category does not exist."


MODULE_ALREADY_CREATED = "This module has already been created."
MODULE_CREATED_SUCCESSFULLY = "Module created successfully."
MODULE_NOT_EXIST = "This module not exist."
MODULE_UPDATED_SUCCESSFULLY = "Module updated successfully."
MODULE_LIST_GET_SUCCESSFULLY = "Module list retrieved successfully."
MODULE_PERMISSION_UPDATED_SUCCESSFULLY = "Module permission updated successfully."
EXPENSES_CREATED_SUCCESSFULLY = "Expense created successfully."
EXPENSES_LIST_GET_SUCCESSFULLY = "Expenses list retrieved successfully."
