USER_CREATE_API = "/"
LOGIN_API = "/login/"
GET_ALL_USERS_LIST_WITH_PAGINATION = "/"
GET_USER_API = "/"
UPDATE_USER_DETAILS = "/"
UPDATE_USER_PASSWORD_DETAILS = "/password_update/"
DELETE_USER_API = "/"

